// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workshop.Api.Data;

#nullable disable

namespace Workshop.Api.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    [Migration("20251002154645_AddAccessRequests")]
    partial class AddAccessRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Workshop.Api.Data.Entities.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservableObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequesterUsername");

                    b.HasIndex("ReservableObjectId");

                    b.HasIndex("Status");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, Downtown",
                            IsActive = true,
                            Name = "Downtown Location"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 North Avenue",
                            IsActive = true,
                            Name = "North Branch"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 East Boulevard",
                            IsActive = true,
                            Name = "East Side Location"
                        });
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.ReservableObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("AvailableUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTimeRestrictions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ReservableObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-A1",
                            OwnerUsername = "john.doe",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 2,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-A2",
                            OwnerUsername = "jane.smith",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 3,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 1,
                            Name = "Desk-A3",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 4,
                            AvailableFrom = new TimeOnly(8, 0, 0),
                            AvailableUntil = new TimeOnly(18, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-B1",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 5,
                            AvailableFrom = new TimeOnly(8, 0, 0),
                            AvailableUntil = new TimeOnly(18, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-B2",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 6,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-C1",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 7,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk-C2",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 8,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Parking-P1",
                            OwnerUsername = "bob.wilson",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 9,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 1,
                            Name = "Parking-P2",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 10,
                            AvailableFrom = new TimeOnly(6, 0, 0),
                            AvailableUntil = new TimeOnly(22, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Parking-P3",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 11,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Parking-P4",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 12,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk-N1",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 13,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk-N2",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 14,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk-N3",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 15,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 2,
                            Name = "Desk-N4",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 16,
                            AvailableFrom = new TimeOnly(9, 0, 0),
                            AvailableUntil = new TimeOnly(17, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk-N5",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 17,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Parking-N1",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 18,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Parking-N2",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 19,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 2,
                            Name = "Parking-N3",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 20,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk-E1",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 21,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk-E2",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 22,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk-E3",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 23,
                            AvailableFrom = new TimeOnly(7, 0, 0),
                            AvailableUntil = new TimeOnly(19, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri,Sat",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk-E4",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 24,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 3,
                            Name = "Desk-E5",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 25,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk-E6",
                            Type = "Desk"
                        },
                        new
                        {
                            Id = 26,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking-E1",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 27,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking-E2",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 28,
                            AvailableFrom = new TimeOnly(6, 0, 0),
                            AvailableUntil = new TimeOnly(20, 0, 0),
                            DaysOfWeek = "Mon,Tue,Wed,Thu,Fri",
                            HasTimeRestrictions = true,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking-E3",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 29,
                            HasTimeRestrictions = false,
                            IsAvailable = false,
                            LocationId = 3,
                            Name = "Parking-E4",
                            Type = "ParkingSpace"
                        },
                        new
                        {
                            Id = 30,
                            HasTimeRestrictions = false,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking-E5",
                            Type = "ParkingSpace"
                        });
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservableObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservableObjectId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.HasIndex("Username");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 1,
                            StartTime = new DateTime(2025, 10, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 8,
                            StartTime = new DateTime(2025, 10, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "jane.smith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 12,
                            StartTime = new DateTime(2025, 10, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "bob.wilson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 20,
                            StartTime = new DateTime(2025, 10, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "alice.brown"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 26,
                            StartTime = new DateTime(2025, 10, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 9, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 2,
                            StartTime = new DateTime(2025, 9, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Username = "jane.smith"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 9, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 17,
                            StartTime = new DateTime(2025, 9, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Username = "bob.wilson"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 10, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservableObjectId = 5,
                            StartTime = new DateTime(2025, 10, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Username = "alice.brown"
                        });
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.AccessRequest", b =>
                {
                    b.HasOne("Workshop.Api.Data.Entities.ReservableObject", "ReservableObject")
                        .WithMany()
                        .HasForeignKey("ReservableObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservableObject");
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.ReservableObject", b =>
                {
                    b.HasOne("Workshop.Api.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Workshop.Api.Data.Entities.ReservableObject", "ReservableObject")
                        .WithMany()
                        .HasForeignKey("ReservableObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservableObject");
                });
#pragma warning restore 612, 618
        }
    }
}
